---
- name: Ensure critical services are running
  hosts: all
  become: yes

  vars:
    services:
      - docker
      - nginx
      - mysql

  tasks:
    - name: Ensure services are enabled and running
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

    - name: Check if Nginx is responding
      uri:
        url: http://localhost
        status_code: 200
      when: "'nginx' in services"

    - name: Check if MySQL is accepting connections
      mysql_ping:
        login_user: root
        login_password: "{{ mysql_root_password }}"
      when: "'mysql' in services"
