---
- name: Ensure services are running
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Ensure Nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
    - name: Ensure MySQL is running
      systemd:
        name: mysql
        state: started
        enabled: yes
