---
- name: Configure Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Deploy nginx.conf
      copy:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
