---
- name: Configure Nginx consistently across environments
  hosts: webservers
  become: yes

  vars:
    nginx_conf_src: "templates/nginx.conf.j2"
    nginx_conf_dest: "/etc/nginx/nginx.conf"
    nginx_sites_available: "/etc/nginx/sites-available"
    nginx_sites_enabled: "/etc/nginx/sites-enabled"
    app_name: "myapp"
    app_domain: "myapp.example.com"
    app_root: "/var/www/myapp"

  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy main nginx.conf
      template:
        src: "{{ nginx_conf_src }}"
        dest: "{{ nginx_conf_dest }}"
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Deploy site configuration
      template:
        src: "templates/site.conf.j2"
        dest: "{{ nginx_sites_available }}/{{ app_name }}"
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Enable site (symlink to sites-enabled)
      file:
        src: "{{ nginx_sites_available }}/{{ app_name }}"
        dest: "{{ nginx_sites_enabled }}/{{ app_name }}"
        state: link
      notify: restart nginx

    - name: Remove default site if present
      file:
        path: "{{ nginx_sites_enabled }}/default"
        state: absent
      notify: restart nginx

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
